### PR TITLE
add new standalone mode for startup

### PR DESCRIPTION
**Pull request by chmorgan**
Bringing this one back since it was helpful in debugging plugin changes that were resulting in crashes.

- motivation: I wanted to be able to debug the UI with PyCharm/vscode
- this is not the most stable thing in the world but gets the job done
- allows the UI to start without Kicad being started, which allows real debugging from an IDE
- see __main__.py for instructions on how to launch this
- wrap all calls to GetBoard() with a class that can return a fake stub

### CODE REVIEW

**Comment by Bouni** [comment]
This does not affect a normal user, right?

**Comment by Bouni** [comment]
@chmorgan Pleae rebase this one so I can test and merge it!

**Comment by chmorgan** [comment]
@Bouni just saw this and the previous ask. Sorry for the delay will rebase this morning and repush.

**Comment by chmorgan** [comment]
@Bouni with expanded use of pcbnew I'd like to clean this one up a bit, will resubmit this afternoon.

Presently it's a bit disjointed, and missing a pcbnew stub so pcbnew.GetSelected() doesn't work, and the naming is not as aligned as I'd like etc. This was highlighted by our more explicit use of pcbnew.XXX functions (a good thing imo) and expanded use of pcbnew functions.

**Comment by Bouni** [comment]
Sure, take your time!

**Comment by chmorgan** [comment]
@Bouni alright, this is the reworked and cleaned up version. Could certainly use review and feedback.

**Comment by Bouni** [comment]
@chmorgan There's a `GetBoard` left in `fabrication.py` https://github.com/Bouni/kicad-jlcpcb-tools/pull/394/files#diff-5a1a96bae787312ee9395f542c62df3cc1e00f5d44c793c2709196cbb9b97e4aL262 that causes the linter to fail

**Comment by chmorgan** [comment]
@Bouni fixed the missing one, tests passing now.

**Comment by Bouni** [comment]
Works on Windows 11 but gives an Error on startup:

grafik

If you click No it continues and starts the app.

**Pull request merged**
