### PR TITLE
Adds support for hierarchical sheets when rewriting schematics files.

### PR DESCRIPTION
**Pull request by gonzalop**
Recursively proceses hierarchical sheets when rewriting schematics files.

### CODE REVIEW

**Comment by chmorgan** [comment]
@gonzalop the plugin already supports generating design packages for hierarchical sheets. Is this adding support to another feature area of the plugin? If so, can the commit subject be clarified?

**Comment by gonzalop** [comment]
Updated. the subject The code makes it rewrite schematics files when exporting changes made by the plugin.

**Comment by chmorgan** [comment]
@gonzalop ahh gotcha, can you update the commit message itself? The subject of the PR might default to the subject of the first commit or something but editing the PR subject doesn't directly edit the commit log message. Should be possible to edit it via 'git commit --amend' or with a git rebase.

**Comment by gonzalop** [comment]
Done.

Thanks.

**Comment by Bouni** [comment]
@chmorgan Did you already test this PR? I have never before used hierarchical sheets in KiCAD, so I canno really test this ...

**Comment by Bouni** [comment]
The export function writes LCSC data that was set via the Plugin back to the schematic.

@gonzalop Can you provide an example project so that I can test this PR?

**Comment by gonzalop** [comment]
Here's an example project: [6-example.prj.zip](https://github.com/user-attachments/files/16433933/6-example.prj.zip)
And here's a screenshot of the output when exporting to schematic:  
Screenshot from 2024-07-30 18-07-55

**Comment by Bouni** [comment]
For whatever reason this does not work for me ...

I run KiCAD 8.0.4

If I extract your zip and open the project, the export to schematic function does not find the correct kicad_sch file because of the `.prj` in the filename. If I then select the right file `6-example.prj.kicad_sch` in this case, the only ozutput I see is 

```
2024.07.31 16:03:12 - INFO - load_schematic -  Kicad 8+...
2024.07.31 16:03:12 - INFO - _update_schematic8 -  Reading C:\Projekte\KiCad\6-example.prj\6-example.prj.kicad_sch...
```

Nothing happens to the `another-sheet.kicad_sch` file.

Furthermore, none of the two resistors in the schematic files gets the LCSC property set ...

**Comment by gonzalop** [comment]
That's odd. It might be some windows oddity. I'll find a windows machine to test on later today and report back.

**Comment by gonzalop** [comment]
It worked for me just now!?
kicad8-windows-sheet

**Comment by Bouni** [comment]
Very strange. Let me look into it on Friday again, tomorrow is a public holiday 😁

**Comment by gonzalop** [comment]
Enjoy the holiday!

FWIW, this was a fresh install of KiCAD 8.0.4 and I cloned the branch with this pull reqeust into the scripting/ folder, the cloned the example project and loaded it up in KiCAD.

**Comment by Bouni** [comment]
Ok, I think I figured it out!

This returns a dict after #487 was merged: https://github.com/Bouni/kicad-jlcpcb-tools/blob/ec4aee04b18e1cbaec767e507dc7d9b3028427c8/schematicexport.py#L47

so this no longer works:

https://github.com/Bouni/kicad-jlcpcb-tools/blob/ec4aee04b18e1cbaec767e507dc7d9b3028427c8/schematicexport.py#L89-L92

replaceing 

```python
                    for part in store_parts:
                        if value == part[0]:
                            newLcsc = part[3]
```

with this

```python
                    for part in store_parts:
                        if value == part["reference"]:
                            newLcsc = part["lcsc"]
```

solves the issue.

Can you please update and rebase your PR

**Comment by gonzalop** [comment]
Done.

**Pull request merged**
