### PR TITLE
[emergency fix] attempt to allow startup even if we can't download the database

### PR DESCRIPTION
**Pull request by binary1230**
JLCPCB's CSV URL stopped working 5 days ago, and the plugin hasn't really had to handle this case so things can get weird. This fix attempts to work around and re-enable exporting and other features while we figure out a more long-term fix (better data source etc).

See #241 and #238 for more info

This is far from a comprehensive and well-tested "offline mode", but it gets the job done for me enough to export fab files, BOM, and POS files.  This could probably use a lot of testing.

future work:
- this could use some more UI polish to indicate better what's going on and what the consequences of that will be. for now it works as an emergency fix.
- pull using a cached data source (I have one, will try and work that into a future PR)

### CODE REVIEW

**Comment by Bouni** [comment]
I'll merge this as an emergency fix, I've tested it just roughly and hope it doesnt't break anything 🤞🏽

**Comment by binary1230** [comment]
Cool, appreciate it. Yea sucks they broke the API.

If I get some more time this week I'll try and make this a little nicer, there's some situations where it's best to still delete parts.db by hand. We could probably warn the users a little more that it's expected that they get a 404 or something.

At least this fix will help with exports, which is still an awesome use of the plugin, even if the parts search stays bricked

**Comment by Bouni** [comment]
@binary1230 I have a parts db from the 23rd of November, so pretty much the most recent state before they broke it.
I think I'll supply that from one of my webservers or put it into the repo. Not sure whats smarter ...
The database has ~480MB but zip compressed its just 58MB.

Any thoughts on this?

**Comment by binary1230** [comment]
Yea, awesome.

I think shipping with it might not be a bad idea if it's only 58mb, especially since it looks like you already have some build scripts that could package it up into the zip that people download via kicad plug-in manager.

GitHub gets weird about files in the repo itself over.... I think 10mb unless you enablr LFS support which gets weird and sometimes expensive even for free public repos.

But if you hosted it on a webserver and had your build scripts download it when it makes the package, that's probably no issue

Then what you could maybe do is have the plugin try and download the URL, and if it 404s, display a message that the parts DB will be an older cached version, and that we're aware of an issue so for now they have to use the JLC site for the actual searching.

That's just kinda initial thoughts, if you have any other way in mind I'm sure it'll be fine. We all appreciate your efforts, sorry JLC Is wasting yours and everyone else's time with something they really should have foreseen and been proactive about

**Comment by binary1230** [comment]
If you want another maintainer btw during this hecticness, happy to jump in, I'm pretty reliant on this plugin for a bunch of upcoming production runs I'm doing for a few PCBs, so plan on keeping an eye on stuff regardless.

**Pull request merged**
