### PR TITLE
Convert wx.Bitmap to wx.Icon for DataViewIconText

### PR DESCRIPTION
**Pull request by kalanzun**
Note: Not tested for wx.BitmapBundle

### CODE REVIEW

**Comment by kalanzun** [comment]
I've changed the pull request. It now introduces a new helper "loadIconScaled". Only DataViewIconText requires an Icon, all other uses of loadBitmapScaled seem to require a Bitmap.

**Comment by kalanzun** [comment]
By the way, why is this code there anyway? All it does is load an empty Icon?

**Comment by kalanzun** [comment]
Ah, found it. It shall load the icons "mdi-check-color.png" and "mdi-close-color.png". The filenames went missing during refactor (in fix-179).

**Comment by Bouni** [comment]
@kalanzun Thats exactly how I wanted it to be, thanks!

**Pull request merged**
