### PR TITLE
[feat] Add resuming download feature for LCSC database

### PR DESCRIPTION
**Pull request by Oliver0804**
- Implemented the feature to resume downloading the LCSC database to handle interrupted downloads
- Referenced Issue #536 and completed the required implementation

### CODE REVIEW

**Comment by Oliver0804** [comment]
Thank you for your correction! I was just about to start, and you already fixed it—haha!

**Comment by Bouni** [comment]
No problem 😅

I test your PR right now. It seems to work as expected, but the progress bar is no longer working.
Would you mind take a look at that?

**Comment by Oliver0804** [comment]
ok!let me check where the code went wrong.

**Comment by Bouni** [comment]
I had a look and it was just two lines you removed, probably by accident. 
To speed things up, I re-added them for you.

**Pull request merged**
