### PR TITLE
Check wxWidgets version 

### LINKED ISSUE #181: Error:  AttributeError: module 'wx' has no attribute 'BitmapBundle'
Hi, 

Thank you for this excellent tool. With the latest version (6.0.3) I get the following error while trying to use the plugin on MacOS/OS X. Sadly I never used it before on OS X, so not sure if it's a new error or not. It seems to work on Windows.

```
Traceback (most recent call last):

File "/Users/username/Documents/KiCad/6.0/3rdparty/plugins/com_github_bouni_kicad-jlcpcb-tools/plugin.py", line 21, in Run
dialog = JLCPCBTools(None)

File "/Users/username/Documents/KiCad/6.0/3rdparty/plugins/com_github_bouni_kicad-jlcpcb-tools/mainwindow.py", line 183, in __init__
loadBitmapScaled(

File "/Users/username/Documents/KiCad/6.0/3rdparty/plugins/com_github_bouni_kicad-jlcpcb-tools/helpers.py", line 53, in loadBitmapScaled
return wx.BitmapBundle(bmp)

AttributeError: module 'wx' has no attribute 'BitmapBundle'
```

### PR DESCRIPTION
**Pull request by Bouni**
Check wxWidgets version in order to decide wether to use Bitmap or BitmapBundle for button icons and static Icons.
Hopefully fixes #181 on all platforms 🤞🏽

### CODE REVIEW

**Comment by kalanzun** [comment]
Seems that DataViewIconText requires a wx.Icon instead of a wx.Bitmap. #185 fixes it for wxWidgets 3.0.5; then, it works for me.

**Comment by alec-deason** [comment]
I see the same error as kalanzun and their branch works for me on arch linux

```
Application: KiCad PCB Editor
Version: (6.0.6), release build
Libraries:
    wxWidgets 3.0.5
    libcurl/7.83.1 OpenSSL/1.1.1p zlib/1.2.12 brotli/1.0.9 zstd/1.5.2 libidn2/2.3.2 libpsl/0.21.1 (+libidn2/2.3.0) libssh2/1.10.0 nghttp2/1.47.0
Platform: Linux 5.18.6-arch1-1 x86_64, 64 bit, Little endian, wxGTK, , wayland
Build Info:
    Date: Jun 21 2022 02:56:58
    wxWidgets: 3.0.5 (wchar_t,wx containers,compatible with 2.8) GTK+ 3.24
    Boost: 1.79.0
    OCC: 7.5.3
    Curl: 7.83.1
    ngspice: 37
    Compiler: GCC 12.1.0 with C++ ABI 1017
Build settings:
    KICAD_USE_OCC=ON
    KICAD_SPICE=ON
    ```

**Comment by Bouni** [comment]
Thanks @kalanzun for your efforts, I tested with KiCAD 6.0.5 on Ubuntu, 6.0.6 on Win 10 and 6.99 on Win 10 and all work for me.
Hopefully this solves the wxwidgets version difference issues on all platforms 🤞🏽

**Comment by timcooijmans** [comment]
Thanks! Also works on OS X.

**Comment by Bouni** [comment]
Thanks for the feedback @timcooijmans highly appreciate it!

**Pull request merged**
