### PR TITLE
partselector.py - Print out the time it took to complete the search n…

### PR DESCRIPTION
**Pull request by chmorgan**
…ext to the row count. Visiblity into search time will let us more easily know if we are optimizing it.

### CODE REVIEW

**Comment by Bouni** [comment]
Please fix checks by formatting with black / sort imports with isort

**Comment by Bouni** [comment]
@chmorgan You might have to rebase all your PRs as I merge a large set of changes a few minutes ago.

**Comment by chmorgan** [comment]
@Bouni yep, I see it. Happy to have the linting and checking in place, looking to confirm this PR will fail (as I didn't reorder imports) and then I'll correct.

**Comment by chmorgan** [comment]
@Bouni how firm are you on the black errors? Splitting up the long conditional line, imo, makes it more difficult to read...

**Comment by Bouni** [comment]
> @Bouni how firm are you on the black errors? Splitting up the long conditional line, imo, makes it more difficult to read...

That's a personal preferenc in my opinion, I find both ways good to read but would like to stick to the default black way of doing things and not start having exceptions here an there.

**Comment by chmorgan** [comment]
@Bouni and I'm not using the pre-commit hooks but I should be

**Comment by Bouni** [comment]
I just added pylint to the pre-commit hooks as well as the GH actions. Intall them py simply type `pre-commit` (do a `pip install pre-commit` first if not already done)

**Comment by chmorgan** [comment]
@Bouni yep, spotted that in the README and have them installed here now.

**Comment by chmorgan** [comment]
@Bouni this one look ok to merge? I think it will still be helpful when looking at the search times to know how long they take.

**Comment by Bouni** [comment]
Sure, I somehow thought this one was depending on the fts5 PR 😅

**Pull request merged**
