### PR TITLE
Replace JLCPCB CSV download with Fallback sqlite db download

### PR DESCRIPTION
**Pull request by Bouni**
As long as JLCPCB doesn't com up with a new way to download their parts catalog we download the last state from 2022-11-23 and use that.

### CODE REVIEW

**Comment by Bouni** [comment]
@binary1230 Would you mind testing this PR? I replaced the CSV download with the download of the parts db from the 23rd, I guess thats the best workaround for the moment ...

**Comment by binary1230** [comment]
Sure I'll try and get to it today

**Comment by tmolteno** [comment]
Working here on Debian testing (see comment on Issue #241)

**Comment by Bouni** [comment]
@tmolteno I'll make some minor changes as suggested by @binary1230 and then merge this.
Then you can install via PCM, no need for downloading the zip anymore.

**Comment by binary1230** [comment]
Sorry I was slammed this whole week, sounds like it's working and looks good at a glance. Thanks so much for all of this.

**Pull request merged**
