### PR TITLE
library.py: search() - fts5 search improvement for keywords shorter t…

### PR DESCRIPTION
**Pull request by chmorgan**
…han 3 unicode characters

FTS5 'match' only evaluates substrings longer than 3 unicode characters, searching for shorter substrings results in no matches being returned.

Fixes an issue where attempting to search for substrings shorter than 3 characters was resulting in empty search results.

Add "AND description LIKE '%SUBSTRING%'" terms for each substring shorter than 3 characters.

### CODE REVIEW

**Comment by chmorgan** [comment]
@whmountains can you give this a shot?

**Comment by whmountains** [comment]
Thanks for this @chmorgan 

I may be doing something wrong, but it's not working for me.  When I type in a two-letter query, it continues displaying the results of the previous, longer query.

I added some some logging to find the problem:

```
2024.04.25 10:09:26 - INFO - search -  evaluating keyword `2k`
2024.04.25 10:09:26 - INFO - search -  using LIKE query for `2k`: `AND description LIKE '%2k%'`
2024.04.25 10:09:26 - INFO - search -  Executing query: SELECT "LCSC Part","MFR.Part","Package","Solder Joint","Library Type","Stock","Manufacturer","Description","Price" FROM parts WHERE parts MATCH ''AND description LIKE '%2k%' AND "Library Type" IN ("Basic") ORDER BY "LCSC Part" COLLATE naturalsort ASC LIMIT 1000
Traceback (most recent call last):
  File "/Users/cw/Documents/KiCad/8.0/scripting/plugins/chmorgan-kicad-tools/partselector.py", line 587, in search
    result = self.parent.library.search(parameters)
  File "/Users/cw/Documents/KiCad/8.0/scripting/plugins/chmorgan-kicad-tools/library.py", line 218, in search
    return cur.execute(query).fetchall()
sqlite3.OperationalError: fts5: syntax error near ""
```
Something funny is going on when there is nothing to match.: `WHERE parts MATCH ''AND`

**Comment by chmorgan** [comment]
Doh, I’ll fix tonight. We may be assuming there is always a match term.

Thanks for the test run.

**Comment by chmorgan** [comment]
@whmountains alright, updated and should fix the issue you saw.

**Comment by chmorgan** [comment]
@whmountains ping on whether this addresses your issues. Would like to get it merged in for quality of life improvements for anyone using the plugin.

**Comment by whmountains** [comment]
Can confirm this PR now works correctly with searches less than 3 chars.

:shipit:

**Comment by chmorgan** [comment]
Any updates on this @Bouni ? Would like to get this and the other PR merged for quality of use improvements for present users.

**Comment by chmorgan** [comment]
Ahh ok, np, have a good vacation!

**Comment by Bouni** [comment]
LGTM

**Pull request merged**
